import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
export const metadata = {
    title: "Register",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <ClerkProvider afterSignOutUrl="/sign-in">
                <html lang="en">
                    <body
                        className={`public`}
                    >
                        {children}
                    </body>
                </html>
            </ClerkProvider>
        </>
    );
}
