import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Navbar from "@/components/shared/Navbar";
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Threads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ClerkProvider appearance={
        {
          baseTheme: dark
        }
      }>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-950 text-white`}
          >
            <main className="relative">
              <div className="top">
                <Navbar />
              </div>
              <div className="left">
              <LeftSidebar />
              </div>
              <section className='main-container'>
                <div className=''>
                  {children}
                </div>
              </section>
              <div className="right border-yellow-700">
                <RightSidebar />
              </div>
              <div className="bottom">
                <Bottombar />
              </div>
            </main>
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
